### PR TITLE
Atomic fence implementation

### LINKED ISSUE #1063: Missing type validation opcode handling for ATOMIC_FENCE
When trying to parse a module built with the threads proposal I'm getting:
```
java.lang.IllegalArgumentException: Missing type validation opcode handling for ATOMIC_FENCE
    at com.dylibso.chicory.wasm.Validator.validateFunction (Validator.java:2147)
    at com.dylibso.chicory.wasm.Validator.validateFunctions (Validator.java:631)
    at com.dylibso.chicory.wasm.WasmModule$Builder.build (WasmModule.java:275)
    at com.dylibso.chicory.wasm.Parser.parse (Parser.java:244)
    at com.dylibso.chicory.wasm.Parser.parse (Parser.java:221)
```
Chicory version 1.5.2

### PR DESCRIPTION
**Pull request by andreaTP**
Fix #1063 

I still don't have a meaningful example to test, but this implementation should enable receiving feedback and iteratively improve.

Reference:
https://webassembly.github.io/threads/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-atomic-memory-mathsf-atomic-fence

and

https://github.com/WebAssembly/threads/blob/33b2dcd6a933f5e3c4b860fbbc4d89077256a2aa/proposals/threads/Overview.md?plain=1#L434

### CODE REVIEW

File: runtime/src/main/java/com/dylibso/chicory/runtime/OpcodeImpl.java [hunk 1]
```diff
@@ -867,4 +868,45 @@ public static void TABLE_INIT(
...
         }
     }
+
+    private static final Runnable ATOMIC_FENCE_IMPL;
+
+    static {
+        Runnable impl;
+        try {
+            // to take into account older Android API level:
+            // https://developer.android.com/reference/java/lang/invoke/VarHandle#fullFence()
```
Comment (evacchi) [inline runtime/src/main/java/com/dylibso/chicory/runtime/OpcodeImpl.java:878]: 🔥

**Review by evacchi — APPROVED** [review]
