### PR TITLE
Fix flaky testgen

### LINKED ISSUE #139: Flaky code generation
At times the test code generator fails with errors even in CI, we should be able to narrow down the issues and have a more stable build.

### PR DESCRIPTION
**Pull request by andreaTP**
Fix #139

### CODE REVIEW

**Comment by andreaTP** [comment]
Tested on quite a few CI runs, this should be stable now:
https://github.com/andreaTP/chicory/actions/runs/7451456239

File: test-gen-plugin/src/main/java/com/dylibso/chicory/maven/JavaTestGen.java [hunk 1]
```diff
@@ -115,12 +102,7 @@ public CompilationUnit generate(
         var testClass = cu.addClass(testName);
         if (ordered) {
             testClass.addSingleMemberAnnotation(
-                    "TestMethodOrder",
-                    new ClassExpr(
-                            JAVA_PARSER
-                                    .parseType("MethodOrderer.OrderAnnotation")
-                                    .getResult()
-                                    .get()));
```
Comment (andreaTP) [inline test-gen-plugin/src/main/java/com/dylibso/chicory/maven/JavaTestGen.java:123]: For the records, the JavaParser issue was in this type lookup.
The rest of the fixes are to tackle other failures that I have observed.

**Review by danielperano — APPROVED** [review]

File: test-gen-plugin/src/main/java/com/dylibso/chicory/maven/JavaTestGen.java (hunk 1 above)
Comment (bhelx) [reply test-gen-plugin/src/main/java/com/dylibso/chicory/maven/JavaTestGen.java:123]: Nice catch!
